DEV-1667: Add external lead link button
LoanGurus/partner-portal pull request #30
Opened 2022-01-18 17:32 UTC by ShiftyMcCool

This adds a button that generates a link to the external add lead page.

[changelog]
added: DEV-1667: Add external lead link button

ps-id: F1A846EF-278F-42E1-89B7-FEF2FD616567

2022-01-18 21:52 UTC, sierra-henderson requested changes

2022-01-18 21:52 UTC, sierra-henderson commented on src/app/graphql/queries.graphql
> -
still need the onboarding queries

2022-01-18 21:55 UTC, ShiftyMcCool commented on src/app/graphql/queries.graphql
> -
It's still there, look at the whole file, i just removed what appeared to be duplicates

2022-01-20 00:04 UTC, sierra-henderson approved these changes

2022-01-20 12:46 UTC, merged