Dev 1583 sign up
LoanGurus/partner-portal pull request #6
Opened 2021-12-15 01:54 UTC by sierra-henderson

[changelog]
added: DEV-1583 Partner can signup/register for the partner portal

2021-12-15 01:56 UTC, sierra-henderson commented
This PR contains the sign up screen, along with a temporary message on the bottom noting that a verification has been sent to a user's email. The verification modal and sign in routing will be addressed in future tickets.

2021-12-15 11:33 UTC, jazzdragon requested changes
- Please make sure we don't add noise by copying over code that will be dead because it's not relevant to this repo.
- Fix tests

2021-12-15 11:33 UTC, jazzdragon commented on src/app/graphql/cache.ts
> +  typePolicies: {
Please remove these typePolicies, they're not relevant to the partner portal.

2021-12-15 11:33 UTC, jazzdragon commented on src/app/graphql/mutations.graphql
> +mutation uploadUrl($input: UploadUrlArgsInput!) {
We don't need all of these mutations, please remove.

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/interfaces/maintenance.interface.ts
> +export interface MaintenanceMode {
Why did you copy this over?

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/interfaces/user-role.interface.ts
> +export enum UserRole {
Why did you copy this over?

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/interfaces/user-session.interface.ts
> +export interface RememberedDevice {
Not needed

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/interfaces/user-session.interface.ts
> +export interface DeviceAttributes {
Not needed

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/interfaces/user-session.interface.ts
> +type UserChallenge =
Is this needed?

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/services/app.service.ts
> +export interface IConfigSettings {
Some of these are not relevant

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/services/maintenance.service.ts
> +import { HttpClient, HttpHeaders } from '@angular/common/http'
why did you copy this over?

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/services/routing-data.service.ts
> +import { Injectable } from '@angular/core'
why did you copy this over?

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/services/user-role.service.ts
> +import { LocalStorageManagementService } from './local-storage-management.service'
why did you copy this?

2021-12-15 11:33 UTC, jazzdragon commented on src/app/shared/services/user-session.service.ts
> +import { AppService } from './app.service'
Please go over this and remove whatever is not relevant

2021-12-15 11:33 UTC, jazzdragon commented on src/assets/app.config.json
> +{
we don't need all of this.

2021-12-15 11:33 UTC, jazzdragon commented on src/environments/environment.ts
> +  amplitudeApiKey: '93cbe14f0b6783fa3a4c6f9223875a10',
Not relevant

2021-12-15 11:33 UTC, jazzdragon commented on src/main.ts
> +Sentry.init({
Remove until we add sentry to the repo

2021-12-15 11:33 UTC, jazzdragon commented on src/app/app.component.ts
> +    this.maintenanceService.fetchMaintenanceMode()
remove

2021-12-15 15:55 UTC, sierra-henderson commented on src/app/shared/interfaces/maintenance.interface.ts
> +export interface MaintenanceMode {
Wasn't sure if we'd be using maitenance mode in this app, I'll remove

2021-12-15 16:00 UTC, sierra-henderson commented on src/app/shared/interfaces/user-session.interface.ts
> +type UserChallenge =
It is used in type `ICognitoUser` which is used in the `UserSessionService`

2021-12-16 11:34 UTC, jazzdragon approved these changes
Looks better. A couple of things:

- The header font seems to not load: https://capture.dropbox.com/WsQubaIIuls8EDiK?src=ss
- Please add the Uqual logo and fix the title (https://capture.dropbox.com/ckJdealvfCyEoiox?src=ss)

2021-12-16 16:49 UTC, merged