Dev 1587 leads list
LoanGurus/partner-portal pull request #61
Opened 2022-01-31 20:46 UTC by sierra-henderson

2022-02-02 11:23 UTC, jazzdragon requested changes
Looks good. Please move the leads components into a components folder in the leads folder.
A few comments / questions, if they're out of scope please create tickets for them:

- Leads who hasn't signed up yet show up as blank rows. I think we should have a message there or something instead.
- There's a weird spinner for the leads form up top. Do we need a loading state? it's just an empty form.
- [minor] Getting this error in the console when reordering by date added: https://capture.dropbox.com/PUZs7ZDXK87bKC95?src=ss
- shouldn't the date added be the date the lead was added by the partner?
- Please use the table wrapper component I made for the referrals page.
- After adding a lead in the form above, I expect it to be added to the table. The cache needs to be updated, I did the same for the referrals form + table, you can check that out.

2022-02-02 20:29 UTC, ShiftyMcCool commented
> Looks good. Please move the leads components into a components folder in the leads folder. A few comments / questions, if they're out of scope please create tickets for them:
> 
> * Leads who hasn't signed up yet show up as blank rows. I think we should have a message there or something instead.
Pinged Kyle about this, Sarah will add design
> * There's a weird spinner for the leads form up top. Do we need a loading state? it's just an empty form.
The form needs the partner's ID so is waiting for the partner service to make it available.  Looks like a static height was added to the loading wrapper after the form was added that causes the spinner to appear below the form.  I'll add a ticket to work this out
> * [minor] Getting this error in the console when reordering by date added: https://capture.dropbox.com/PUZs7ZDXK87bKC95?src=ss
I hate this error... "fixed"
> * shouldn't the date added be the date the lead was added by the partner?
Confirmed with Kyle that it is the enrollment date, changed header
> * Please use the table wrapper component I made for the referrals page.
Nice
> * After adding a lead in the form above, I expect it to be added to the table. The cache needs to be updated, I did the same for the referrals form + table, you can check that out.
Haven't gotten this working yet, will open additional ticket for it

2022-02-03 09:56 UTC, jazzdragon approved these changes

2022-02-03 14:36 UTC, jazzdragon commented
This is already approved

2022-02-03 17:19 UTC, merged