DEV-1805: Show loan amount as approximate
LoanGurus/partner-portal pull request #87
Opened 2022-02-24 20:01 UTC by ShiftyMcCool

[changelog]
changed: DEV-1805: Show loan amount as approximate

ps-id: C3816C38-E004-4A4A-ABEA-319EADBE7C04

2022-02-24 22:35 UTC, sierra-henderson requested changes

2022-02-24 22:35 UTC, sierra-henderson commented on src/app/leads/components/leads-table/leads-table.component.html
> +<ng-template #loanAmountColumn let-value="value">
Make sure tilde only shows up if we have a loan amount value

2022-02-25 12:53 UTC, ShiftyMcCool commented on src/app/leads/components/leads-table/leads-table.component.html
> +<ng-template #loanAmountColumn let-value="value">
good call, didn't even notice.  fixed

2022-02-25 16:08 UTC, sierra-henderson approved these changes

2022-02-25 21:40 UTC, merged